add touch_raw diagnostic
CMU-cabot/cabot-drivers pull request #7
Opened 2024-02-20 07:46 UTC by miyazakifuki

2024-02-21 01:49 UTC, dsato80 requested changes
ACE以外でも使うコードなので、少し変更をお願いします。

2024-02-21 01:49 UTC, dsato80 commented on cabot_serial/include/cabot_serial/cabot_serial.hpp
> +
ACE特有のメッセージをここに置きたくないですね…。
cabot-arduino-aceの方からメッセージを送るようにできないでしょうか？
そうすれば、メッセージを追加してもこちらに変更を加える必要がありません。

2024-02-21 01:49 UTC, dsato80 commented on cabot_serial/include/cabot_serial/cabot_serial.hpp
> +
set_touch_raw_statusはtaskの方に移動しませんか？
getが不要になります。

2024-02-21 01:49 UTC, dsato80 commented on cabot_serial/include/cabot_serial/cabot_serial.hpp
> +  std::string touch_raw_diag_message_;
int touch_raw_status_;
  std::string touch_raw_diag_message_;

こちらも同様にtaskの方に移動

2024-02-21 01:49 UTC, dsato80 commented on cabot_serial/include/cabot_serial/cabot_serial.hpp
> +  std::shared_ptr<CaBotSerialNode> node_;
ノードを見る必要はないので、直接ステータスをタスクに設定するようにしてください。（後述）

2024-02-21 01:49 UTC, dsato80 commented on cabot_serial/src/cabot_serial.cpp
> +  touch_raw_diag_message_("working")
移動

2024-02-21 01:49 UTC, dsato80 commented on cabot_serial/src/cabot_serial.cpp
>  }
これはTouch rawのメッセージがarduinoが来た時だけ設定しませんか？
GTやその他のマシンではデフォルトでは使わないので。

2024-02-21 01:49 UTC, dsato80 commented on cabot_serial/src/cabot_serial.cpp
> +  }
ここでtaskのインスタンスがなければ作り、taskに直接ステータスとメッセージを設定してください。

2024-02-21 02:27 UTC, miyazakifuki commented on cabot_serial/include/cabot_serial/cabot_serial.hpp
> +
> ACE特有のメッセージをここに置きたくないですね…。
> cabot-arduino-aceの方からメッセージを送るようにできないでしょうか？
> そうすれば、メッセージを追加してもこちらに変更を加える必要がありません。

こちらに関しては文字列だとデータサイズが大きくなると思ってあえてcabot側に置くようにしました。
arduinoから送った方が良いでしょうか？

2024-02-21 08:10 UTC, miyazakifuki commented
コメントの対応しました。

2024-02-21 17:04 UTC, dsato80 approved these changes
基本はこれで良いと思います。
接続が切れた場合に最後に設定されたステータスで表示され続けるのだけ気になりました。コネクションの方でエラーになるので、実用的には問題ないと思いますが。

ステータスを受け取った時刻を記録しておいて、runが実行された時に3秒以上古ければstaleにするとかでしょうか

2024-02-22 01:55 UTC, miyazakifuki commented
@dsato80 
追加しました！

2024-02-22 03:27 UTC, merged